import { Metadata } from 'next';
import Head from 'next/head';
import React from 'react';

export const metadata: Metadata = {
  title: 'root page',
  description: 'Generated by Cool Chaeyeon',
};

const page = () => {
  return (
    <Head>
      <meta
        name='google-site-verification'
        content='Ot9R1wLIt3DP15IpoikrTHTptAcVxD5f-MX5poEjgrQ'
      />
      <meta
        name='naver-site-verification'
        content='f92dce300102fa2c730313dc1f2fc4c907edcc93'
      />
      page
    </Head>
  );
};

export default page;
