import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'root page',
  description: 'Generated by Cool Chaeyeon',
};

const page = () => {
  return <div>page</div>;
};

export default page;
